### ISSUE TITLE
Textures messed up

### ISSUE THREAD

**Issue by carlosedubarreto** [NVlabs/nvdiffrecmc#1]
First of all. the work you guys are doing is amazing...

And testing the solution I noticed one odd thing.
When I run the code for the first time, it goes very well, but if I run it a second time, thigs get messy.

Here is a result of running Bob example the second time
![image](https://user-images.githubusercontent.com/4061130/194748971-7958eb6a-cdcd-4714-a250-fcc4541da423.png)

The same happens in the https://github.com/NVlabs/nvdiffrec

Do you know what I can do the have a good result when executing a second time?

Thanks a lot

**Comment by JHnvidia** [comment]
Hi Carlos,

I think this is a file/permission issue. The texture coordinates are stores in the .obj file while textures are stored as separate .pngs. It seems like we're not able to overwrite the textures (either because of file permissions or because the files are open by another program) but able to overwrite the mesh. That would explain why the texture map looks strange.

As a workaround please try and rename or delete the mesh folder before rerunning the program.

**Comment by carlosedubarreto** [comment]
Sorry for the trouble, now I understood the problem.
Its not fault of nvdiffrec, but from Blender.

If I load an OBJ, blender creates the shader automatically, when I add another object that uses the same texture name, blender is going to reuse the one that is already loaded.

So the solution to my problem is really simple. Close and open Blender again.

Thanks a lot for the attention and for spend the time to answer.
